apiVersion: v1
kind: Service
metadata:
  name: deployment-apache-nginx-service-nodeport
spec:
  selector:
    app: myapp        # Matches both pods
  ports:
  - protocol: TCP
    port: 80          # Service Port
    targetPort: 80    # Pod Port
    nodePort: 30080   # NodePort (optional, can be auto-assigned)
  type: NodePort